// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kygiwnhxczfalwfqlxqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5Z2l3bmh4Y3pmYWx3ZnFseHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDQ4NTAsImV4cCI6MjA2NzkyMDg1MH0.h-ycJ8mElF_paYmlF1G97XKnFseFMDJplmz7NTonIgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});